// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb4TAio2AqZw1-ov5eRsaSPNZa8ynnlXk',
    appId: '1:817370875039:web:c2b16e136ffbdc89c2ceaa',
    messagingSenderId: '817370875039',
    projectId: 'videocallapp-89910',
    authDomain: 'videocallapp-89910.firebaseapp.com',
    storageBucket: 'videocallapp-89910.appspot.com',
    measurementId: 'G-PPVV025QZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoewzII9Fzf7hpfxvkaqINyTM8sm-4f1Y',
    appId: '1:817370875039:android:9b9d2bc9efed652fc2ceaa',
    messagingSenderId: '817370875039',
    projectId: 'videocallapp-89910',
    storageBucket: 'videocallapp-89910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYIdhRQ59XMtegq6_STIExqV0OldbHj9U',
    appId: '1:817370875039:ios:b673bd1285ed506ec2ceaa',
    messagingSenderId: '817370875039',
    projectId: 'videocallapp-89910',
    storageBucket: 'videocallapp-89910.appspot.com',
    androidClientId: '817370875039-27hf6s439nl1a0c105hd81hgnv47uc06.apps.googleusercontent.com',
    iosClientId: '817370875039-rhr1g2p6gubbmkngea0uoae2mrlbgsgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYIdhRQ59XMtegq6_STIExqV0OldbHj9U',
    appId: '1:817370875039:ios:b673bd1285ed506ec2ceaa',
    messagingSenderId: '817370875039',
    projectId: 'videocallapp-89910',
    storageBucket: 'videocallapp-89910.appspot.com',
    androidClientId: '817370875039-27hf6s439nl1a0c105hd81hgnv47uc06.apps.googleusercontent.com',
    iosClientId: '817370875039-rhr1g2p6gubbmkngea0uoae2mrlbgsgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb4TAio2AqZw1-ov5eRsaSPNZa8ynnlXk',
    appId: '1:817370875039:web:2669c0edf3051058c2ceaa',
    messagingSenderId: '817370875039',
    projectId: 'videocallapp-89910',
    authDomain: 'videocallapp-89910.firebaseapp.com',
    storageBucket: 'videocallapp-89910.appspot.com',
    measurementId: 'G-N8K8QEWJ8N',
  );
}
