-keep class com.facebook.jni.** { *; }
-keep class com.facebook.react.** { *; }
-dontwarn com.facebook.react.**
-dontwarn com.squareup.okhttp.**
-keep class com.squareup.okhttp.** { *; }
-dontwarn okhttp3.**
-keep class okhttp3.** { *; }
-dontwarn org.conscrypt.**
-dontwarn com.google.common.**
-dontwarn org.codehaus.mojo.**
